# Generated by Django 4.2 on 2023-08-28 03:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("authentication", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="StreamLineSubscription",
            fields=[
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="usersubscription",
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("Premium", models.BooleanField(default="False")),
                ("Basic", models.BooleanField(default="False")),
                ("Premium_Expiration", models.DateField(blank=True, null=True)),
                ("Basic_Expiration", models.DateField(blank=True, null=True)),
                (
                    "stripe_customer_id",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "stripe_subscription_id",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("is_setup", models.BooleanField(default="False")),
            ],
        ),
        migrations.CreateModel(
            name="TOSChecked",
            fields=[
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="toschecked",
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("TOS_Checked", models.BooleanField(default="False")),
            ],
        ),
        migrations.CreateModel(
            name="UserContactRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_email", models.CharField(max_length=100)),
                ("user_first_name", models.CharField(max_length=100)),
                ("user_last_name", models.CharField(max_length=100)),
                ("user_message", models.CharField(max_length=1000)),
                ("user_phone_number", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="UserSettings",
            fields=[
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="usersettings",
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("First_Name", models.CharField(max_length=100)),
                ("Last_Name", models.CharField(max_length=100)),
                ("Street_Address", models.CharField(max_length=100)),
                ("City", models.CharField(max_length=100)),
                ("State_Province", models.CharField(max_length=100)),
                ("Country", models.CharField(default="United States", max_length=100)),
                ("Postal_Code", models.CharField(max_length=6)),
                ("Newsletter", models.BooleanField(default="True")),
                ("Promotions", models.BooleanField(default="True")),
                (
                    "Push_Notifications",
                    models.CharField(
                        choices=[
                            ("Everything", "Everything"),
                            ("SameAsEmail", "Same as Email"),
                            ("None", "None"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "Email",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="settings_email",
                        to=settings.AUTH_USER_MODEL,
                        to_field="email",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("budget", models.CharField(max_length=10)),
                ("bundle", models.JSONField(default=dict)),
                ("media", models.JSONField(default=list)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ThirdPartySubscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("subscription_name", models.CharField(max_length=100)),
                (
                    "subscription_price",
                    models.DecimalField(decimal_places=2, max_digits=6),
                ),
                ("subscription_image_path", models.CharField(max_length=100)),
                ("end_date", models.DateField(blank=True, null=True)),
                ("num_months", models.IntegerField(default=0)),
                ("num_cancellations", models.IntegerField(default=0)),
                ("subscription_version", models.CharField(max_length=100)),
                ("subscription_status", models.CharField(max_length=100)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subscription",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
