# Generated by Django 4.2 on 2023-09-18 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("settings", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="thirdpartysubscription",
            name="subscription_next_action",
            field=models.CharField(default="None", max_length=100),
        ),
    ]
